# Dependencies
markdown: kramdown
gems: [jekyll-paginate]

# Permalinks
permalink: :year/:month/:title/
highlighter : rouge

# Setup
title: SHINOBU KAWANO
tagline: 'JavaScript / UX Design / Enterprise Mobility / and Travel ✈✈'
description: > #
  Hi, there! I'm Shinobu Kawano, JavaScript programmer based in Tokyo.
  <br>
  I work for my favorite company
  <a href='http://www.sencha.com/' target='_blank'>Sencha</a>,
  where I'm dedicated to improving the UX of Japanese business applications higher as the global standard level.

url: http://shinobukawano.com
baseurl: '/'
paginate: 5

author:
  name: 'Shinobu Kawano'
  url: http://shinobukawano.com

exclude: ["vendor",".rbenv-version", ".gitignore", "README.md", "Gemfile", "Gemfile.lock", "Procfile", "unicorn.rb", "config.ru"]

# Misc
future: true
