# Dependencies
markdown: redcarpet
gems: [jekyll-paginate]

# Permalinks
permalink: :year/:month/:title/
highlighter : pygments

# Setup
title: Shinobu Kawano
tagline: 'JavaScript / Java / Enterprise Mobility / and Travel ✈✈'
description: > #
  Hi, there! I'm Shinobu Kawano, JavaScript programmer based in Tokyo.
  I work for my most loving software vendor
  <a href='http://www.sencha.com/' target='_blank'>Sencha</a> as a sales engineer.
  <br>In my spare time, I hack an open source software and spend time with my wife and son.

url: http://kawanoshinobu.com
baseurl: '/'
paginate: 5

author:
  name: 'Shinobu Kawano'
  url: http://kawanoshinobu.com

exclude: ["vendor",".rbenv-version", ".gitignore", "README.md", "Gemfile", "Gemfile.lock", "Procfile", "unicorn.rb", "config.ru"]
